import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import SessionProvider from "@/providers/session-provider";
import NextUIProviders from "@/providers/nextui-provider";
import MainSideBar from "@/components/sidebar/main-sidebar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProvider>
      <html lang="en">
        <body
          className={`${inter.className} block md:grid md:grid-cols-[250px_1fr] min-h-screen bg-gray-50`}>
          <div className="hidden md:block">
            <MainSideBar />
          </div>
          <div className="">
            <Navbar />
            <div className="px-6">
              <NextUIProviders>{children}</NextUIProviders>
            </div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
